name: mobx_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # A
  # B
  better_player: ^0.0.83
  # C
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  # D
  dio: ^5.1.2
  data_state_mobx: ^0.1.0
  # E
  easy_localization: ^3.0.2
  # F
  flutter_flavor: ^3.1.1
  flutter_mobx: ^2.0.6+5
  f_logs: ^2.0.1
  firebase_crashlytics: ^3.4.8
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  # G
  get_it: ^7.6.0
  # I
  # J
  json_serializable: ^6.6.2
  # K
  # L
  # M
  mobx: ^2.0.7
  # N
  # O
  # P
  # Q
  # R
  # S
  shared_preferences: ^2.1.1
  # T
  # U
  # V
  # W
  # X
  # Y
  # Z

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  injectable_generator: ^2.1.5  # this will help the injectable to generate injectable files automatically otherwise we have to do it manually
  analyzer: ^5.12.0
  mobx_codegen: ^2.3.0


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
